/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  /**
   * All users with online offline status
   */
  users: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * unique username
     */
    username?: string;
    status?: "ONLINE" | "OFFLINE";
  };
}
